version: '3'

services:
  loadbalancer:
    build: ./nginx
    ports:
      - "8080:80"
  app1:
    image: app
    environment: 
      - APP_ID=1
    ports:
      - "5001:5000"
  app2:
    image: app
    environment: 
      - APP_ID=2
    ports:
      - "5002:5000"
  app3:
    image: app
    environment: 
      - APP_ID=3
    ports:
      - "5003:5000"