version: '3'

services:
  loadbalancer:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx:/etc/nginx/
  app1:
    image: app
    environment: 
      - PORT=1111
    expose:
      - "1111"
  app2:
    image: app
    environment: 
      - PORT=2222
    expose:
      - "2222"
  app3:
    image: app
    environment: 
      - PORT=3333
    expose:
      - "3333"